#!/usr/bin/env python3
"""Train and evaluate the AIRA alternative credit scoring model.

This script loads the model-ready dataset generated by feature_engineering.py,
filters out rows that should be handled by non-score gates (fraud_flag and
insufficient_history), trains a multiclass credit-risk model, evaluates it,
and saves the trained artifact plus SHAP-based feature importance.

Expected dataset columns (from training_dataset.csv):
- user_id, persona, months_of_history, n_transactions, income_regularity,
  avg_monthly_income, savings_ratio, bill_payment_count,
  bill_payment_regularity, transaction_diversity, spending_to_income_ratio,
  balance_volatility, max_single_txn_pct_balance, circular_transfer_flag,
  balance_consistency_pass, composite_score, risk_label, tier

The scoring model is trained only on eligible borrowers:
- low_risk
- medium_risk
- high_risk

Rows labeled as insufficient_history or fraud_flag are excluded from the
multiclass score model because they are handled explicitly by the governance
layer described in the whitepaper.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, List

import joblib
import numpy as np
import pandas as pd
import shap
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


TARGET_ORDER = ["low_risk", "medium_risk", "high_risk"]
EXCLUDED_LABELS = {"insufficient_history", "fraud_flag"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train the AIRA alternative credit scoring model.",
    )
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path(__file__).resolve().parent / "training_dataset.csv",
        help="Path to the training dataset CSV.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "artifacts",
        help="Directory where model artifacts and metrics will be stored.",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.2,
        help="Fraction of data to reserve for validation.",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed used for train/test split.",
    )
    parser.add_argument(
        "--model",
        choices=["xgboost", "lightgbm", "both"],
        default="both",
        help="Which model family to train; both compares both and selects the best.",
    )
    return parser.parse_args()


def default_feature_columns() -> List[str]:
    """Return the behavior features used for the credit score model."""
    return [
        "months_of_history",
        "n_transactions",
        "income_regularity",
        "avg_monthly_income",
        "savings_ratio",
        "bill_payment_count",
        "bill_payment_regularity",
        "transaction_diversity",
        "spending_to_income_ratio",
        "balance_volatility",
        "max_single_txn_pct_balance",
        "circular_transfer_flag",
        "balance_consistency_pass",
    ]


def build_label_mapping() -> Dict[str, int]:
    return {label: idx for idx, label in enumerate(TARGET_ORDER)}


def prepare_dataset(data_path: Path) -> tuple[pd.DataFrame, pd.Series, List[str]]:
    """Load training data and build the scoring-ready dataset."""
    if not data_path.exists():
        raise FileNotFoundError(f"Training dataset not found at: {data_path}")

    df = pd.read_csv(data_path)
    df = df.copy()

    if "risk_label" not in df.columns:
        raise ValueError(f"Dataset does not contain the required 'risk_label' column: {data_path}")

    excluded = df["risk_label"].isin(EXCLUDED_LABELS)
    eligible = df.loc[~excluded].copy()

    if eligible.empty:
        raise ValueError(
            "No eligible rows remain after excluding insufficient_history and fraud_flag. "
            "Check the dataset and labels."
        )

    y = eligible["risk_label"].copy()

    # Drop only metadata fields that are not part of the learned feature set.
    drop_cols = ["user_id", "persona", "tier", "risk_label", "composite_score"]
    for col in drop_cols:
        if col in eligible.columns:
            eligible = eligible.drop(columns=[col])

    feature_cols = default_feature_columns()
    missing = [col for col in feature_cols if col not in eligible.columns]
    if missing:
        raise ValueError(f"Missing feature columns in dataset: {missing}")

    X = eligible[feature_cols].copy()

    # Keep the labels in a consistent, risk-aware order for model training.
    label_to_idx = build_label_mapping()
    y_encoded = y.map(label_to_idx)

    # Make sure the valid labels exist in the selected dataset.
    valid_labels = set(TARGET_ORDER)
    if not set(y.unique()).issubset(valid_labels):
        unexpected = sorted(set(y.unique()) - valid_labels)
        raise ValueError(f"Unexpected target labels found: {unexpected}")

    return X, y_encoded, feature_cols


def train_xgboost(X_train: pd.DataFrame, y_train: pd.Series, random_state: int):
    model = XGBClassifier(
        objective="multi:softprob",
        num_class=len(TARGET_ORDER),
        n_estimators=400,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        random_state=random_state,
        eval_metric="mlogloss",
        n_jobs=-1,
    )
    model.fit(X_train, y_train)
    return model


def train_lightgbm(X_train: pd.DataFrame, y_train: pd.Series, random_state: int):
    model = LGBMClassifier(
        objective="multiclass",
        num_class=len(TARGET_ORDER),
        n_estimators=400,
        learning_rate=0.05,
        max_depth=-1,
        num_leaves=31,
        subsample=0.9,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        random_state=random_state,
        n_jobs=-1,
        verbose=-1,
    )
    model.fit(X_train, y_train)
    return model


def evaluate_model(
    model,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    feature_cols: List[str],
    reverse_mapping: Dict[int, str],
    output_dir: Path,
    model_name: str,
) -> Dict[str, float]:
    pred_numeric = model.predict(X_test)
    pred_labels = [reverse_mapping[int(value)] for value in pred_numeric]
    y_true_labels = [reverse_mapping[int(value)] for value in y_test.to_numpy()]

    metrics = {
        "accuracy": float(accuracy_score(y_true_labels, pred_labels)),
        "f1_macro": float(f1_score(y_true_labels, pred_labels, average="macro")),
        "f1_weighted": float(f1_score(y_true_labels, pred_labels, average="weighted")),
    }

    report = classification_report(
        y_true_labels,
        pred_labels,
        labels=TARGET_ORDER,
        output_dict=True,
        zero_division=0,
    )

    metrics["classification_report"] = report

    try:
        explainer = shap.Explainer(model, X_test)
        shap_values = explainer(X_test)
        values = shap_values.values

        # SHAP for multiclass models can return a 3D array shape:
        # (n_samples, n_features, n_classes). Flatten to mean absolute importance.
        if isinstance(values, np.ndarray) and values.ndim == 3:
            mean_abs = np.abs(values).mean(axis=0)
            mean_abs = mean_abs.mean(axis=1)
        else:
            mean_abs = np.abs(values).mean(axis=0)

        shap_summary = pd.DataFrame({
            "feature": feature_cols,
            "mean_abs_shap": mean_abs,
        }).sort_values("mean_abs_shap", ascending=False)

        shap_path = output_dir / f"{model_name}_shap_summary.csv"
        shap_summary.to_csv(shap_path, index=False)
        metrics["shap_summary_path"] = str(shap_path)
    except Exception as exc:  # pragma: no cover - best effort for explainability layer
        metrics["shap_error"] = str(exc)

    metric_path = output_dir / f"{model_name}_metrics.json"
    with metric_path.open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=2, default=str)

    return metrics


def save_model_artifact(model, output_dir: Path, model_name: str):
    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / f"{model_name}.joblib"
    joblib.dump(model, model_path)
    return model_path


def choose_best_model(results: Dict[str, Dict[str, float]]) -> str:
    return max(results, key=lambda name: results[name]["f1_macro"])


def main():
    args = parse_args()
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    X, y_encoded, feature_cols = prepare_dataset(args.data_path)
    reverse_mapping = {idx: label for label, idx in build_label_mapping().items()}

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y_encoded,
        test_size=args.test_size,
        random_state=args.random_state,
        stratify=y_encoded,
    )

    candidates = {}

    if args.model in {"xgboost", "both"}:
        xgb_model = train_xgboost(X_train, y_train, args.random_state)
        xgb_metrics = evaluate_model(
            xgb_model,
            X_test,
            y_test,
            feature_cols,
            reverse_mapping,
            output_dir,
            "xgboost",
        )
        save_model_artifact(xgb_model, output_dir, "xgboost")
        candidates["xgboost"] = xgb_metrics

    if args.model in {"lightgbm", "both"}:
        lgb_model = train_lightgbm(X_train, y_train, args.random_state)
        lgb_metrics = evaluate_model(
            lgb_model,
            X_test,
            y_test,
            feature_cols,
            reverse_mapping,
            output_dir,
            "lightgbm",
        )
        save_model_artifact(lgb_model, output_dir, "lightgbm")
        candidates["lightgbm"] = lgb_metrics

    if not candidates:
        raise ValueError("No model was trained. Check the selected --model option.")

    best_name = choose_best_model(candidates)
    metadata = {
        "training_dataset": str(args.data_path),
        "feature_columns": feature_cols,
        "target_order": TARGET_ORDER,
        "best_model": best_name,
        "score_scale": "0-100 product score",
        "limitations": [
            "This model is trained on synthetic transaction patterns, not verified historical repayment outcomes.",
            "The PDF/CSV parser is a practical extraction layer and may misclassify edge-case bank statement rows.",
            "The user-facing score is a risk-band score for product UX, not a calibrated credit bureau score.",
            "Final underwriting decisions should use a regulator-reviewed model with real repayment data.",
        ],
        "results": candidates,
    }

    metadata_path = output_dir / "training_metadata.json"
    with metadata_path.open("w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2, default=str)

    print("Training complete.")
    print(f"Best model by macro-F1: {best_name}")
    for name, metrics in candidates.items():
        print(f"{name}: accuracy={metrics['accuracy']:.4f}, f1_macro={metrics['f1_macro']:.4f}, f1_weighted={metrics['f1_weighted']:.4f}")
    print(f"Metadata saved to: {metadata_path}")


if __name__ == "__main__":
    main()
